name: gastos_compartidos
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Asegúrate de tener el SDK compatible con Dart 3.x

dependencies:
  flutter:
    sdk: flutter

  # Firebase y Firestore (ya integrados en tu proyecto)
  cloud_firestore: ^5.4.4
  
  # Gestión de estado
  scoped_model: ^2.0.0 

  # Iconos y UI
  cupertino_icons: ^1.0.8  # Compatible con Flutter 3.x
  flutter_vector_icons: ^2.0.0

  # Plugins adicionales
  page_transition: ^2.0.4
  animated_bottom_navigation_bar: ^0.3.2
  fl_chart: ^0.40.6
  date_time_picker: ^2.0.0
  intl: ^0.17.0
  select_form_field: ^2.0.0
  url_launcher: ^6.0.20
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  file_picker: ^5.2.10
  animations: ^2.0.0
  screenshot: ^3.0.0
  pie_chart: ^5.1.0
  sqflite: ^2.0.1
  share_plus: ^6.3.1
  image_gallery_saver: ^1.7.1           # Para formateo de fechas y números

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/budget.png"

  flutter_lints: ^5.0.0      # Buenas prácticas y convenciones de codificación

# Configuración para Flutter
flutter:
  uses-material-design: true

  # Incluye los recursos que necesitas para las imágenes y fuentes en tu proyecto.
  assets:
    - assets/images/         # Ruta a imágenes utilizadas en la aplicación


