// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8u4a8GoT5sHayp5cGNbvlYOvQdmOSEs8',
    appId: '1:42136239303:web:bd4e063ca993677078d2e2',
    messagingSenderId: '42136239303',
    projectId: 'gastos-compartidos-272cc',
    authDomain: 'gastos-compartidos-272cc.firebaseapp.com',
    storageBucket: 'gastos-compartidos-272cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXK_kae9oApMu8TVxwLPmNNBjgF6S1Lwg',
    appId: '1:42136239303:android:ed3a92b346e46c9178d2e2',
    messagingSenderId: '42136239303',
    projectId: 'gastos-compartidos-272cc',
    storageBucket: 'gastos-compartidos-272cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA28YqSaLWe89_-2HTffQJ0asHc80lxcQ8',
    appId: '1:42136239303:ios:decba6f07eb9c6d478d2e2',
    messagingSenderId: '42136239303',
    projectId: 'gastos-compartidos-272cc',
    storageBucket: 'gastos-compartidos-272cc.appspot.com',
    iosBundleId: 'com.example.gastosCompartidos',
  );
}
