// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGZczbEitWcH7C3rUJsGO6rVwjQF8r-R0',
    appId: '1:317357800424:web:de89a6e63d205b6d10825d',
    messagingSenderId: '317357800424',
    projectId: 'shared-expense-manager-cb26f',
    authDomain: 'shared-expense-manager-cb26f.firebaseapp.com',
    storageBucket: 'shared-expense-manager-cb26f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYFHoS-VKXujvdSRZi9fqFVegaFboHxCY',
    appId: '1:317357800424:android:fefebf6cf7c3aa5310825d',
    messagingSenderId: '317357800424',
    projectId: 'shared-expense-manager-cb26f',
    storageBucket: 'shared-expense-manager-cb26f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnFqcm2lC_JBu-qXqzQqC3F8G8nQKZTzo',
    appId: '1:317357800424:ios:2b818260b369d7f410825d',
    messagingSenderId: '317357800424',
    projectId: 'shared-expense-manager-cb26f',
    storageBucket: 'shared-expense-manager-cb26f.appspot.com',
    iosBundleId: 'com.example.gastosCompartidos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnFqcm2lC_JBu-qXqzQqC3F8G8nQKZTzo',
    appId: '1:317357800424:ios:62b8579ff04de54910825d',
    messagingSenderId: '317357800424',
    projectId: 'shared-expense-manager-cb26f',
    storageBucket: 'shared-expense-manager-cb26f.appspot.com',
    iosBundleId: 'com.example.gastosCompartidos.RunnerTests',
  );
}
